---
- name: Get restore site access token
  shell: curl -X POST -u "{{AUTH_RESOURCE}}:{{AUTH_SECRET}}" -d "grant_type=client_credentials" "{{AUTH_URL}}/realms/{{AUTH_REALM}}/protocol/openid-connect/token"
  register: AUTH_TOKEN
  ignore_errors: true
- name: "Get the {{ JSON }} data"
  uri: 
    headers:
      Authorization: "Bearer {{(AUTH_TOKEN.stdout | from_json).access_token}}"
      Content-Type: "application/json"
    url: "{{COMPUTATE_SCOLAIRE_SITE_BASE_URL_ENUS}}{{DATA_URI}}?fq=pk:{{ JSON.pk }}"
    return_content: true
  register: GET_JSON
  ignore_errors: true
- name: "Debug the {{ JSON }} data"
  debug: 
    msg: "curl -X PATCH -H 'Authorization: Bearer {{(AUTH_TOKEN.stdout | from_json).access_token}}' -H 'Content-Type: application/json' -d '{\"setArchived\":true}' '{{COMPUTATE_SCOLAIRE_SITE_BASE_URL_ENUS}}{{DATA_URI}}?fq=pk:{{ JSON.pk }}'"
  ignore_errors: true
  when: GET_JSON.json.list[0].archived is defined and GET_JSON.json.list[0].archived == false
- name: "Archive the {{ JSON }} data"
#  shell: "curl -X PATCH -H 'Authorization: Bearer {{(AUTH_TOKEN.stdout | from_json).access_token}}' -H 'Content-Type: application/json' -d '{\"setArchived\":true}' '{{COMPUTATE_SCOLAIRE_SITE_BASE_URL_ENUS}}{{DATA_URI}}?fq=pk:{{ JSON.pk }} && sleep {{SLEEP}}"
  shell: "curl -X PATCH -H 'Authorization: Bearer {{(AUTH_TOKEN.stdout | from_json).access_token}}' -H 'Content-Type: application/json' -d '{\"setArchived\":true}' '{{COMPUTATE_SCOLAIRE_SITE_BASE_URL_ENUS}}{{DATA_URI}}?fq=pk:{{ JSON.pk }}'"
  ignore_errors: true
  register: PATCH
  when: GET_JSON.json.list[0].archived is defined and GET_JSON.json.list[0].archived == false
- debug:
    var: PATCH
  when: GET_JSON.json.list[0].archived is defined and GET_JSON.json.list[0].archived == false

