//#############################################
//## file: DefaultJavaCommentParser.java
//## Generated by Byacc/j
//#############################################
package com.thoughtworks.qdox.parser.impl;

/**
 * BYACC/J Semantic Value for parser: DefaultJavaCommentParser
 * This class provides some of the functionality
 * of the yacc/C 'union' directive
 */
public class DefaultJavaCommentParserVal
{
/**
 * integer value of this 'union'
 */
public int ival;

/**
 * double value of this 'union'
 */
public double dval;

/**
 * string value of this 'union'
 */
public String sval;

/**
 * object value of this 'union'
 */
public Object obj;

//#############################################
//## C O N S T R U C T O R S
//#############################################
/**
 * Initialize me without a value
 */
public DefaultJavaCommentParserVal()
{
}
/**
 * Initialize me as an int
 */
public DefaultJavaCommentParserVal(int val)
{
  ival=val;
}

/**
 * Initialize me as a double
 */
public DefaultJavaCommentParserVal(double val)
{
  dval=val;
}

/**
 * Initialize me as a string
 */
public DefaultJavaCommentParserVal(String val)
{
  sval=val;
}

/**
 * Initialize me as an Object
 */
public DefaultJavaCommentParserVal(Object val)
{
  obj=val;
}
}//end class

//#############################################
//## E N D    O F    F I L E
//#############################################
